// <auto-generated />
namespace Kippenbout.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Edited_Register : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edited_Register));
        
        string IMigrationMetadata.Id
        {
            get { return "201611071100201_Edited_Register"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
