// <auto-generated />
namespace Kippenbout.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MenustoMenusList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MenustoMenusList));
        
        string IMigrationMetadata.Id
        {
            get { return "201701191253045_Menus-to-MenusList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
