// <auto-generated />
namespace Kippenbout.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_reservering_Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_reservering_Create));
        
        string IMigrationMetadata.Id
        {
            get { return "201701181443379_change_reservering_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
